baseURL = 'https://meridiano58.com.ar/'
languageCode = 'es-ar'
title = 'Meridiano 58'
[markup.goldmark.renderer]
  unsafe = true
[outputs]
  home = ["HTML", "RSS", "JSON"]
[taxonomies]
  category = "categories"
  tag = "tags"
  perfil = "perfiles"
