baseURL = 'https://meridiano58.com.ar/'
languageCode = 'es-ar'
title = 'Meridiano 58'
[markup.goldmark.renderer]
  unsafe = true
[outputs]
  home = ["HTML", "RSS", "JSON"]
# --- SISTEMA DE TAXONOMÍAS ---
[taxonomies]
  tematica = "tematicas"
